name: Docker Image Scan

on: 
  workflow_call:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t minha-imagem:latest .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.14.0
        with:
          image-ref: minha-imagem:latest
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL